name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set image ver
        id: image_version
        run: echo "gitsha=$(git ver-parse --short HEAD)" >> GITHUB_OUTPUT
      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/yousefqawasmeh/express-docker:${{steps.image_version.output.gitsha}}
        # run: docker build . --file Dockerfile --tag ghcr.io/yousefqawasmeh/express-docker:$(date +%s)
        # run: docker build . --file Dockerfile --tag express-docker:$(date +%s)
      - name: publish docker image
      - run: docker push ghcr.io/yousefqawasmeh/express-docker:${{steps.image_version.output.gitsha}}
